services:
  - type: web
    name: loan-manager-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: OWNER_NAME
        value: Owner
      - key: OWNER_PHONE
        value: 9999999999
      - key: OWNER_PASSWORD
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://lone-manager-app-frontend-tecy-git-main-anujs-projects-63d20f84.vercel.app
      - key: MONGODB_URI
        sync: false
